/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrmAbout.java
 *
 * Created on Nov 10, 2009, 12:01:40 PM
 */

package simplevideoconverter;

/**
 *
 * @author juanki23
 */
public class jfrmAbout extends javax.swing.JFrame {

    /** Creates new form jfrmAbout */
    public jfrmAbout() {
        initComponents();
        super.setLocationRelativeTo(this);
        jbtnLicense.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jbtnLicense = new javax.swing.JButton();
        jLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAbout = new javax.swing.JTextArea();
        jbtnClose1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Simple Video Converter 1.5.1");

        jbtnLicense.setText("License");
        jbtnLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLicenseActionPerformed(evt);
            }
        });
        jbtnLicense.setBounds(250, 150, 90, 31);
        jLayeredPane1.add(jbtnLicense, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SVCLogo.png"))); // NOI18N
        jLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLogo.setBounds(0, 0, 200, 190);
        jLayeredPane1.add(jLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jtxtAbout.setBackground(new java.awt.Color(254, 254, 254));
        jtxtAbout.setColumns(20);
        jtxtAbout.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        jtxtAbout.setRows(5);
        jtxtAbout.setText(" Simple Video Converter 1.5.1\n Written by: Juan C. Núñez\n Required:\n mencoder,dvdauthor, mkisofs.\n Note: mencoder, dvdauthor and mkisofs don't \n          have any responsibility for any bugs in \n          this program.\n https://sourceforge.net/projects/svideoconverter/");
        jScrollPane1.setViewportView(jtxtAbout);

        jScrollPane1.setBounds(200, 0, 290, 130);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbtnClose1.setText("Close");
        jbtnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClose1ActionPerformed(evt);
            }
        });
        jbtnClose1.setBounds(370, 150, 90, 31);
        jLayeredPane1.add(jbtnClose1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLicenseActionPerformed
      new jLicensefrm().setVisible(true);
    }//GEN-LAST:event_jbtnLicenseActionPerformed

    private void jbtnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClose1ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jbtnClose1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmAbout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnClose1;
    private javax.swing.JButton jbtnLicense;
    private javax.swing.JTextArea jtxtAbout;
    // End of variables declaration//GEN-END:variables

}
